name: 🚀 Unit Test check ✅

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pytest
      - name: 🔍 Run pytest
        run: pytest tests/